# Generated by Django 4.0.4 on 2022-05-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_rename_image_entry_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='image_url',
            new_name='image',
        ),
    ]
