# Generated by Django 4.0.4 on 2022-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_rename_image_url_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uploader',
        ),
    ]
