# Generated by Django 4.0.4 on 2022-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_entry_image_alter_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
